[package]
name = "asciify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
termcolor = "1.2.0"
clap = { versions = "4.2.7", features = ["derive"]}
rgb2ansi256 = "0.1.1"